spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:h2:file:./database.h2
    driverClassName: org.h2.Driver
    username: admin
    password: test123
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
  sql:
    init:
      mode: always
  h2:
    console.enabled: true
