//Create a user
POST http://localhost:8080/api/members
Content-Type: application/json

{
  "email": "user1@test.ch",
  "firstname": "User",
  "lastname": "1",
  "cardId": "146213128"
}

###

//Create a second user
POST http://localhost:8080/api/members
Content-Type: application/json

{
  "email": "user2@test.ch",
  "firstname": "User",
  "lastname": "2",
  "cardId": "18518811710"
}

###

//Get Users
GET http://localhost:8080/api/members

###

//Verify a card from User 1
GET http://localhost:8080/api/members/verify/18518811710

###

//Verify a card from User 2
GET http://localhost:8080/api/members/verify/18518811710

###

//BAD CASE - Invalid Card
GET http://localhost:8080/api/members/verify/18518811711

###